### ISSUE TITLE
ENH: Support newline delimited JSON (ndjons/jsonl)

### ISSUE THREAD

**Issue by corneliusroemer** [ynqa/jnv#14] opened 2024-03-21 19:06 UTC
I'd love to use `jnv` with newline delimited json files as well. Right now, when I load an ndjson file, I get the following error:

```
$ jnv ncbi_dataset/data/data_report.jsonl 
Error: trailing characters at line 2 column 1
```

`jq` on the other hand has absolutely no issue with `jsonl` files.

**Comment by edgarrmondragon** [comment] 2024-03-22 02:19
A JSON lines file was the first file I tried to used `jnv` with 😅. Big +1 for this one.

**Comment by ynqa** [comment] 2024-03-23 06:31
Thanks! But it seems to be a duplicate of #9, so I will close it 🙏

**Comment by corneliusroemer** [comment] 2024-03-23 18:46
Hard to find the original as I've never heard of Json stream being used to talk about Jsonl/ndjson.

Could you edit the title of the original to be clearer?

Also maybe close as "duplicate" not as "completed", when I saw the purple completion I was already happy that it was added only to be disappointed that it was closed as duplicate 😇

**Comment by ynqa** [comment] 2024-03-24 01:58
@corneliusroemer 

> Could you edit the title of the original to be clearer?

Sure. But let me confirm what both issues want to say. 

These are adding the functionality that allows filtering over multiple JSON structures contained in a single file/standard input, right?

> Also maybe close as "duplicate" not as "completed", when I saw the purple completion I was already happy that it was added only to be disappointed that it was closed as duplicate 😇

I apologize for changing the issue state on my own. I'll proceed in a way that everyone can agree on. Therefore, please let me reopen it (Even if it is deemed a duplicate again and gets closed) 🙇

**Comment by ynqa** [comment] 2024-03-24 15:14
In #28, we've made it possible to handle multiple JSONs. Please check whether the problem addressed in this issue has been resolved.

**Comment by ynqa** [comment] 2024-03-24 15:14
@corneliusroemer In #28, we've made it possible to handle multiple JSONs. Please check whether the problem addressed in this issue has been resolved.

**Closed** 2024-03-25 11:13 UTC
Labels: feature request, v0.2.0

**Comment by ynqa** [comment] 2024-03-25 11:38
@corneliusroemer v0.2.0, which addresses this issue, has been released. Please check it out 🎉

**Comment by Lewenhaupt** [comment] 2024-03-26 16:44
Installed this last week and didn't get to test it until today when I had a use-case I really needed it for. Encountered the trailing issue, found this issue, updated, and now it works! @ynqa thanks for a great tool :)
